### ISSUE TITLE
Big file size

### ISSUE THREAD

**Issue by franklupo** [jchristn/WatsonDedupe#1]
HI,
I'm implementing a backup for large 100GB files and more. Are there any problems or does the library work well?

Best regards

**Comment by jchristn** [comment]
Hi thanks for your note. For files that size it isn’t yet appropriate because it internally works off of byte arrays. I’m in the process of implementing v1.3 which will support streams and should support your use case well. Likely finished within a week. Cheers

**Comment by jchristn** [comment]
Hi @franklupo out of curiosity are you using .NET Framework or .NET Core?

**Comment by franklupo** [comment]
.net core

Il Ven 12 Lug 2019, 18:42 Joel Christner <notifications@github.com> ha
scritto:

**Comment by jchristn** [comment]
Hi @franklupo I have an early cut of release v1.3 in the following commit.  Not sure if you want to clone/build/test or not but I thought I would share it prior to putting some finishing touches on it.  There is still some memory optimization I'm planning to do, but the stream-based interfaces are working. 
 Cheers, Joel 
   
https://github.com/jchristn/WatsonDedupe/commit/31378bc26f3c8ca4b3ec13fdae8d6edbc556bc72

**Comment by jchristn** [comment]
Cancel that...  Issues found.  More to come.

**Comment by jchristn** [comment]
Hi @franklupo I just committed to master and uploaded v1.3.0.1 to NuGet, please feel free to give it a go and see if it works for you.  This version will better support large files by providing Stream-centric interfaces rather than just byte arrays.  I've also modified the internals to use streams and it is working correctly based on the testing that I've performed.  Please reopen or file another issue to let me know if you see any issues and in particular if you find any objects are not hydrated/retrieved correctly.  I've been using file size checks alongside ```certutil -hashfile <filename>``` to validate.  Cheers, Joel
